# taken from https://nicolas-van.github.io/easy-markdown-to-github-pages/
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md